version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/notifications-core/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    labels:
      - "dependencies"
      - "security"
