version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    dns: 8.8.8.8
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
