// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhiegxnqgjlgpbywujzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoaWVneG5xZ2psZ3BieXd1anpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTM4OTgsImV4cCI6MjA2NTQ2OTg5OH0.zBjwrD5r1zDLHcjQKd0gpU8IVLxfKHuHDeNi7XYkNK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);