name: "\ud83d\udce6 Publish User Profiles Module"

on:
  push:
    tags:
      - 'user-profiles-v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build module
        working-directory: src/modules/userProfiles
        run: npm run build

      - name: Publish to npm
        working-directory: src/modules/userProfiles
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
