name: Release & Publish

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'src/modules/adminDashboard/**'
      - 'package.json'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Bump version
        run: npm version patch --no-git-tag-version
      - name: Generate changelog
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: '@oneLogAfrica/admin-dashboard'
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
