name: Update README & Reports from JSON

on:
  push:
    paths:
      - "project-status.json"
      - "scripts/generate-readme.py"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Python dependencies
        run: |
          pip install markdown weasyprint
      - name: Generate README, CHANGELOG, CONTRIBUTING, ROADMAP, HTML & PDF
        run: |
          python -m project_tracker.scripts.cli build --json project-status.json --readme README.md --template project-tracker/templates/readme_template.md --html project-report.html --pdf project-report.pdf
          python -m project_tracker.scripts.cli changelog --json project-status.json --template project-tracker/templates/changelog_template.md --output CHANGELOG.md
          python -m project_tracker.scripts.cli contributing --template project-tracker/templates/contributing_template.md --output CONTRIBUTING.md
          python -m project_tracker.scripts.cli roadmap --json project-status.json --template project-tracker/templates/roadmap_template.md --output ROADMAP.md
      - name: Commit and push if changed
        run: |
          git config user.name "OneLog Bot"
          git config user.email "bot@onelog.africa"
          git add README.md CHANGELOG.md CONTRIBUTING.md ROADMAP.md project-report.html project-report.pdf
          git diff --cached --quiet || git commit -m "ci: auto-update docs & reports from JSON"
          git push
      - name: Upload HTML & PDF reports as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: onelog-reports
          path: |
            project-report.html
            project-report.pdf
